### ISSUE TITLE
Bart model details

### ISSUE THREAD

**Issue by kruthikakr** [HHousen/DocSum#6]
Hi ..Would you give me which Bart model you have used ? as i see in the code it is bart-large-cnn. But the summarisation results from this are better than what i get for https://huggingface.co/facebook/bart-large-cnn. Can you give me details of this ?

**Comment by HHousen** [comment]
@kruthikakr Possibly this could generate better summaries because of the decoding options used in [L66-L71](https://github.com/HHousen/DocSum/blob/master/bart_sum.py#L66-L71) of [bart_sum.py](https://github.com/HHousen/DocSum/blob/master/bart_sum.py#L66-L71). Other than that, the code just uses the `bart-large-cnn` model from `huggingface/transformers` as you said.
